// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP8yphKv8_1rYq-RmnEOMwHGJFrxwtIjs',
    appId: '1:158006515713:web:f61bb93aa9859aa60e8800',
    messagingSenderId: '158006515713',
    projectId: 'ridemate-e46a7',
    authDomain: 'ridemate-e46a7.firebaseapp.com',
    databaseURL: 'https://ridemate-e46a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ridemate-e46a7.firebasestorage.app',
    measurementId: 'G-RLGPSLQHTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2KH6b8noRAWNEkcGLD9CIOlOIaEzCuvg',
    appId: '1:158006515713:android:0f6593372ea5b0420e8800',
    messagingSenderId: '158006515713',
    projectId: 'ridemate-e46a7',
    databaseURL: 'https://ridemate-e46a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ridemate-e46a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Gfxwovfxw2VBT7vHJLytAXKy47XNTUw',
    appId: '1:158006515713:ios:e410901cde3064a10e8800',
    messagingSenderId: '158006515713',
    projectId: 'ridemate-e46a7',
    databaseURL: 'https://ridemate-e46a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ridemate-e46a7.firebasestorage.app',
    iosBundleId: 'com.ridemate.ridemate',
  );
}
